### PR TITLE
zkwave: w16 and final update

### PR DESCRIPTION
**Pull request by ltfschoen**

### CODE REVIEW

**Comment by taxmeifyoucan** [comment]
The final dev update should be in a separate document as a standalone report. Checkout final updates from previous cohort for some inspiration https://github.com/eth-protocol-fellows/cohort-three/blob/master/development-updates.md

**Comment by ltfschoen** [comment]
@taxmeifyoucan I've moved the final project update into a separate hackmd.io document and updated it

**Comment by taxmeifyoucan** [comment]
Thanks! It's not accessible now, I am getting 403. Please make sure to publish it

**Comment by ltfschoen** [comment]
> Thanks! It's not accessible now, I am getting 403. Please make sure to publish it

sorry i've published it now

**Pull request merged**
