### PR TITLE
weekly update 13

### PR DESCRIPTION
**Pull request by alessandromazza98**
This PR adds my 13th weekly update!

TL;DR:
- finish working on some PR for Reth
- advance the work for reth-crawler (together with an anonymous contributor called 0xprames). We collected more than 10.000 unique peers in the p2p network and we are start building a frontend dashboard in order to display those data

### CODE REVIEW

**Comment by taxmeifyoucan** [comment]
Thanks Alessandro! 
Regarding the crawler, I am wondering if you could maybe work with @angaz to create same API as the existing [node-crawler](https://github.com/ethereum/node-crawler) and reuse its frontend or other components. Might make your life much easier, also I believe you can learn from experience with that project.

**Comment by angaz** [comment]
I have completely reworked the crawler this weekend. I have a page to list the nodes and more information for each node: https://node-crawler.s3fe.io/nodes?network=1&page=1

Something which is different to other crawlers is that it's also accepting connections. So there's a few nodes which we can't connect to from the internet, but the nodes have connected to the crawler, so we have those node's info. I think there's still a lot of missing data because of nodes without port-forwarding, but hey, it's something.

**Comment by alessandromazza98** [comment]
Thanks Mario, definitely I'll contact @angaz to discuss the difference between our implementations. I looked at the repo and I see you're mostly using `devp2p` for the backend. So I have some questions to ask you ahaha

**Comment by alessandromazza98** [comment]
Ehi, @angaz what's the best way to contact you? Didn't find telegram or discord

**Comment by angaz** [comment]
I am @angaz on discord

**Pull request merged**
