### PR TITLE
Development updates

### PR DESCRIPTION
**Pull request by gzanitti**
Development updates: Week 0 & Week 1

### CODE REVIEW

**Review by taxmeifyoucan — CHANGES_REQUESTED** [review]
Thanks for the PR. It seems both links are pointing to week 0 update, please make sure the link is correct

**Comment by gzanitti** [comment]
@taxmeifyoucan thanks Mario! I made a brief summary condensing both weeks hence the repeated link. Do you want me to remove one of the entries?

**Comment by taxmeifyoucan** [comment]
Yes, please don't post the same updates in row, just add to the week column it belongs to. Thanks!

**Comment by gzanitti** [comment]
> Yes, please don't post the same updates in row, just add to the week column it belongs to. Thanks!

Done 👍🏻. Thanks!

**Comment by gzanitti** [comment]
@taxmeifyoucan sorry for the delay, now it's ready :)
I updated both texts, in case you want to read them again.

**Comment by taxmeifyoucan** [comment]
Looks great! Thanks a lot

**Pull request merged**
