### PR TITLE
stateless Account Abstraction, EIP-x.md

### PR DESCRIPTION
**Pull request by sogolmalek**

### CODE REVIEW

**Review by taxmeifyoucan — CHANGES_REQUESTED** [review]
Thanks for adding the project! I have the same comment as in https://github.com/eth-protocol-fellows/cohort-four/pull/13#pullrequestreview-1509119153

I find it bit too early to add the whole project to the repo now, I would recommend posting at least a first dev update and getting some feedback from mentors regarding the project specs. However, if you already did your research and collected some feedback, I am open to merging this of course!

**Comment by sogolmalek** [comment]
Thank you so much Mario! Oh yes absolutely, I’m keen to evolve the whole project under the supervision of top tier core devs and get better. I believe  the intro live meeting on 13th will give me clear instructions on how to proceed the fellowship in best way. Looking very forward to it Cheers, Sogol Sent from my iPhone On 9. Jul 2023, at 14:04, Mário Havel ***@***.***> wrote:﻿
@taxmeifyoucan requested changes on this pull request.

Thanks for adding the project! I have the same comment as in #13. #13 (review)
I find it bit too early to add the whole project to the repo now, I would recommend posting at least a first dev update and get feedback from mentors regarding the project specs. However, if you already did your research and collected some feedback, I am open to merging this of course!

**Comment by lfzkoala** [comment]
Let's kick off!

**Comment by taxmeifyoucan** [comment]
Hey @sogolmalek, these weeks is better timing to submit the project proposal. Please feel free to update the doc and let me know when it's ready to be merged

**Comment by sogolmalek** [comment]
@taxmeifyoucan Thank you so much,Sounds great, Ill make sure to submit it by the end of week in correct template :)

**Pull request closed without merging**
